name: "Test GHA - Number Square"
description: "A GHA that takes an input number and returns its square"
inputs:
  num:
    description: "Enter a number:"
    required: true
    default: "1"
outputs:
  num_squared:
    description: "Square of the number:"
    value: ${{steps.get-square.outputs.num_squared}}
runs:
  using: composite
  steps:
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install requirements
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass inputs to shell
      run: |
              echo "INPUT_NUM=${{inputs.num}}" >> $GITHUB_ENV
      shell: bash
    - name: Get the number's square"
      id: get-square
      run: python src/get_num_square.py
      shell: bash
  